#!/bin/bash

# Hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

# Check for Oh My Zsh and install if we don't have it
if test ! $(which omz); then
  /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/HEAD/tools/install.sh)"
fi

# Check for Homebrew and install if we don't have it
if test ! $(which brew); then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# Add global gitignore
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
git config --global core.excludesfile $HOME/.global-gitignore

# Removes .zshrc from $HOME (if it exists) and symlinks the .zshrc file from the .dotfiles
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc

# Activate z
cd ~/.dotfiles/shell
chmod +x z.sh

# Install composer
echo 'Install composer'
echo '----------------'
EXPECTED_CHECKSUM="$(php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')"
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"

if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]
then
    >&2 echo 'ERROR: Invalid installer checksum'
    rm composer-setup.php
    exit 1
fi

php composer-setup.php --quiet
RESULT=$?
rm composer-setup.php
exit $RESULT

# Install node
echo 'Install node'
echo '-----------'
brew install nvm
mkdir ~/.nvm
source ~/.zshrc

nvm install 16
nvm alias default 16

echo 'Install pkg-config'
echo '------------------'
brew install pkg-config

echo 'Install wget'
echo '------------'
brew install wget --overwrite

echo 'Install php'
echo '-----------'
brew tap shivammathur/php
brew install shivammathur/php/php@8.0
brew install shivammathur/php/php@7.4
# brew install shivammathur/php/php@7.3

echo 'Install imagemagick'
echo '-------------------'
brew install imagemagick

# Install PHP extensions with PECL
echo 'Install PHP extensions with PECL'
echo '---------------'
brew install zlib # Needed for Memcached
pecl install imagick memcached redis swoole

echo 'Install xdebug'
echo '--------------'
pecl install xdebug

echo 'Install Laravel Installer'
echo '---------------------'
composer global require "laravel/installer"

echo 'Install Laravel Envoy'
echo '---------------------'
composer global require "laravel/envoy"

echo 'Install Laravel Valet'
echo '---------------------'
composer global require laravel/valet
valet install

echo 'Install Expose'
echo '---------------------'
composer global require beyondcode/expose

echo 'Install ghostscript'
echo '-------------------'
brew install ghostscript

echo 'Install zsh-autosuggestions'
echo '---------------------------'
brew install zsh-autosuggestions

echo 'Install image optimisation tools'
echo '---------------------------'
brew install ffmpeg
brew install jpegoptim
brew install optipng
brew install pngquant
brew install svgo
brew install gifsicle

echo 'Install MAS (Mac App Store manager)'
echo '---------------------------'
brew install mas

# Create a Sites directory
mkdir $HOME/Sites

# Set macOS preferences - we will run this last because this will reload the shell
source $HOME/.dotfiles/macos/set-defaults.sh

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'All done!'
echo 'Things to do to make the agnoster terminal theme work:'
echo '1. Install menlo patched font included in ~/.dotfiles/misc https://gist.github.com/qrush/1595572/raw/Menlo-Powerline.otf'
echo '2. Install patched solarized theme included in ~/.dotfiles/misc'

echo '++++++++++++++++++++++++++++++'
echo 'Some optional tidbits'

echo '1. Install Applications by running: $HOME/.dotfiles/macos/apps.sh'
echo '2. Make a .dotfiles-custom/shell/.aliases for your personal commands'

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
